---
- name: Install Ruby, Git and Bundler
  hosts: all
  become: true
  tasks:
  - name: Apt update and install ruby-full ruby-bundler build-essential
    apt:
      pkg:
      - ruby-full
      - ruby-bundler
      - build-essential
      - git
      update_cache: yes
